# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'LandmarkRemark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Analytics
  pod 'Firebase/Analytics'

  # Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  
end
